cookie:  
  expiry_days: 30  
  key: "some_signature_key"  # Replace with your actual signature key  
  name: "auth_cookie"        # Replace with your desired cookie name  
  
credentials:  
  usernames:  
    yonatanr:  
      email: yonatanr@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Yonatan Rabinovich  
      password: "$2b$12$YqibkUQNnd4n7mYKJC7lLOqnDLWq8dsOx3hqburynTY6NURuFmt4y"  # Hash of the password  
    avit:  
      email: avit@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Avi Tuval  
      password: "$2b$12$gi7BLBNq9fRBoFCwiGkO9eDG4O4tMEZc8CEp9Ui0yPwxS7IbCT7H."  # Hash of the password  
    aya:  
      email: aya@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Aya Efrati  
      password: "$2b$12$tqbOG3AtI/1LjvAgkE19D.Rb7lJtTXfR2H5ZTQmzWNxt5qCEtvpSm"  # Hash of the password  
    naorg:  
      email: naorg@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Naor Gutman  
      password: "$2b$12$iYczoz2ikyOFpn822niSBuqJkJaEiMmGue0jbbRsRj.qPuUMzaeOy"  # Hash of the password  
    shaiel:  
      email: shaiel@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Shai Elkayam  
      password: "$2b$12$CZzJDW6l0dXAVas0Q3NqJOneQb/VfHU0q8cTOESoJQmLPEs5P48hq"  # Hash of the password  
    yahels:  
      email: yahels@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Yahel Shay  
      password: "$2b$12$ZLC3B6rkTb0a0L0d4y9RHuJz4fL.L6pFfYOo84hx7k5vTvr2suIci"  # Hash of the password  
    yairc:  
      email: YairC@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Yair Cohen  
      password: "$2b$12$DdjKQdBFEMdvd7UW1mhnmOgjwhZnFfLMJdEnxXloxJOjzf4jXW8Qe"  # Hash of the password  
    taly:
      email: taly@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Tal Yefet  
      password: "$2b$12$NTSQ4nGlq8XSUXH4xk4opOL7dRMuhZiWuOh7qDCLQ0mMFielkF2vi"  # Hash of the password  
    alonh:
      email: alonh@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Alon Hanochi  
      password: "$2b$12$6/sT5TM2Y9fBL3s7BWuJaOfVaiNS31f4SNwod0WEjWyC3iMJB14Kq"  # Hash of the password  
    tzvika:
      email: tzvika@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Tzvika Brotman
      password: "$2b$12$h2VqCEuWTqonJYNRsF8f..3niI7Y5HSCUdzhSPlPdrzstm23eDH5O"  # Hash of the password  
    asafbr:   
      email: asafbr@diplomat-global.com          
      failed_login_attempts: 0          
      logged_in: false          
      name: Asaf Braha        
      password: "$2b$12$58FXR9CsoZkqu26sWfjice0gr0Tf.WYAYJTcqC911n8SACGmxxOrm"  # Hash of the password    
    chenk:   
      email: chenk@diplomat-global.com          
      failed_login_attempts: 0          
      logged_in: false          
      name: Chen Kremer        
      password: "$2b$12$Zd4jHuazXzX0pM8npDVsSuOqYSoeog6DFU4ih5IYseskW4OGuQFMy"  # Hash of the password    
    Janal:  
      email: Janal@diplomat-global.com          
      failed_login_attempts: 0          
      logged_in: false          
      name: Jana Lefton        
      password: "$2b$12$oO9n.xy8jmQ4wY/eN7pqOu53dwUCYUgnGYvryok6tvx/SljK16XWq"  # Hash of the password          
    miritn:   
      email: miritn@diplomat-global.com          
      failed_login_attempts: 0          
      logged_in: false          
      name: Mirit Niv        
      password: "$2b$12$AxwuqBWB4XY77VvtBN7smutofvbgltwDqRHroj605Duuvq7cErG8G"  # Hash of the password         
    liata:   
      email: liata@diplomat-global.com          
      failed_login_attempts: 0          
      logged_in: false          
      name: Liat Binyamin        
      password: "$2b$12$rrcPxL0ezj3fRh.aYP/2JuYOjPNco51K6WpN.Vm5K3bDHv9hgheu."  # Hash of the password   


pre-authorized:  
  emails:  
    - ryonatan6@gmail.com  