cookie:  
  expiry_days: 30  
  key: "some_signature_key"  # Replace with your actual signature key  
  name: "auth_cookie"        # Replace with your desired cookie name  
  
credentials:  
  usernames:  
    yonatanr:  
      email: yonatanr@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Yonatan Rabinovich  
      password: "$2b$12$YqibkUQNnd4n7mYKJC7lLOqnDLWq8dsOx3hqburynTY6NURuFmt4y"  # Hash of the password  
    avit:  
      email: avit@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Avi Tuval  
      password: "$2b$12$gi7BLBNq9fRBoFCwiGkO9eDG4O4tMEZc8CEp9Ui0yPwxS7IbCT7H."  # Hash of the password  
    aya:  
      email: aya@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Aya Efrati  
      password: "$2b$12$tqbOG3AtI/1LjvAgkE19D.Rb7lJtTXfR2H5ZTQmzWNxt5qCEtvpSm"  # Hash of the password  
    naorg:  
      email: naorg@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Naor Gutman  
      password: "$2b$12$iYczoz2ikyOFpn822niSBuqJkJaEiMmGue0jbbRsRj.qPuUMzaeOy"  # Hash of the password  
    shaiel:  
      email: shaiel@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Shai Elkayam  
      password: "$2b$12$CZzJDW6l0dXAVas0Q3NqJOneQb/VfHU0q8cTOESoJQmLPEs5P48hq"  # Hash of the password  
    yahels:  
      email: yahels@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Yahel Shay  
      password: "$2b$12$ZLC3B6rkTb0a0L0d4y9RHuJz4fL.L6pFfYOo84hx7k5vTvr2suIci"  # Hash of the password  

pre-authorized:  
  emails:  
    - ryonatan6@gmail.com  