cookie:  
  expiry_days: 30  
  key: "some_signature_key"  # Replace with your actual signature key  
  name: "auth_cookie"        # Replace with your desired cookie name  
  
credentials:  
  usernames:  
    yonatanr:  
      email: yonatanr@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Yonatan Rabinovich  
      password: "$2b$12$YqibkUQNnd4n7mYKJC7lLOqnDLWq8dsOx3hqburynTY6NURuFmt4y"  # Hash of the password  
    avit:  
      email: avit@diplomat-global.com  
      failed_login_attempts: 0  
      logged_in: false  
      name: Avi Tuval  
      password: "$2b$12$gi7BLBNq9fRBoFCwiGkO9eDG4O4tMEZc8CEp9Ui0yPwxS7IbCT7H."  # Hash of the password  
  
pre-authorized:  
  emails:  
    - ryonatan6@gmail.com  